[build]
  command = "yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# SPA fallback — redirect mọi URL về index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
